version: '2'
services:
  wpe:
    restart: always
    build: ./wpe
    privileged: true
    environment:
      WPE_URL: http://localhost:8080

  scheduler:
    restart: always
    build: ./scheduler
    privileged: true

  server:
    restart: always
    build: ./server
    privileged: true
